import { ROUTER_URL, TOPIC_CLASSIFICATIONS } from './constants';

export const lessons = [
  // Contracts
  {
    id: 1,
    topic: 'Contracts',
    phonetic: '/ˈkɒntrækts/',
    classification: TOPIC_CLASSIFICATIONS.GENERAL_BUSINESS.value,
    routerURL: ROUTER_URL.CONTRACT,
    image: 'https://www.craigpanterlaw.com/wp-content/uploads/sites/2240/2016/10/Contract-Review.jpg',
    vietnamese: 'Hợp đồng',
  },
  {
    id: 2,
    topic: 'Marketing',
    phonetic: '/ˈmɑːkɪtɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.GENERAL_BUSINESS.value,
    routerURL: ROUTER_URL.MARKETING,
    image: 'http://study.com/cimages/course-image/principles-of-marketing-syllabus-resource-lesson-plans_139082_large.jpg',
    vietnamese: 'Kinh doanh',
  },
  {
    id: 3,
    topic: 'Warranties',
    phonetic: '/ˈwɒrənti/',
    classification: TOPIC_CLASSIFICATIONS.GENERAL_BUSINESS.value,
    routerURL: ROUTER_URL.WARRANTIES,
    image: 'https://thumbs.dreamstime.com/b/warranty-hologram-futuristic-interface-augmented-virtual-reality-warranty-hologram-futuristic-interface-augmented-virtual-reality-99390520.jpg',
    vietnamese: 'Bảo hành',
  },
  {
    id: 4,
    topic: 'Businness Planning',
    phonetic: '/ˈbɪznəs/ /ˈplænɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.GENERAL_BUSINESS.value,
    routerURL: ROUTER_URL.BUSINESS_PLANNING,
    image: 'http://bitsofdays.com/wp-content/uploads/2018/07/Planning-your-business.jpg',
    vietnamese: 'Kế hoạch công việc',
  },
  {
    id: 5,
    topic: 'Conferences',
    phonetic: '/ˈkɒnfərəns/',
    classification: TOPIC_CLASSIFICATIONS.GENERAL_BUSINESS.value,
    routerURL: ROUTER_URL.CONFERENCES,
    image: 'https://3b6xlt3iddqmuq5vy2w0s5d3-wpengine.netdna-ssl.com/state-of-security/wp-content/uploads/sites/3/coTuqBm5SKiBjQqRqvxpkg_thumb_4e1-800x450.jpg',
    vietnamese: 'Hội nghị',
  },
  // Office issues
  {
    id: 6,
    topic: 'Computers',
    phonetic: '/kəmˈpjuːtər/',
    classification: TOPIC_CLASSIFICATIONS.OFFICE_ISSUES.value,
    routerURL: ROUTER_URL.COMPUTERS,
    image: 'https://www.imeche.org/images/default-source/default-album/computer-code-main.jpg?sfvrsn=0',
    vietnamese: 'Máy vi tính',
  },
  {
    id: 7,
    topic: 'Office Technology',
    phonetic: '/ˈɒfɪs/ /tekˈnɒlədʒi/',
    classification: TOPIC_CLASSIFICATIONS.OFFICE_ISSUES.value,
    routerURL: ROUTER_URL.OFFICE_TECHNOLOGY,
    image: 'http://mquest-technologies.com/en/wp-content/uploads/2010/05/image-8-800x450.jpg',
    vietnamese: 'Công nghệ văn phòng',
  },
  {
    id: 8,
    topic: 'Office Procedures',
    phonetic: '/ˈɒfɪs/ /prəˈsiːdʒər/',
    classification: TOPIC_CLASSIFICATIONS.OFFICE_ISSUES.value,
    routerURL: ROUTER_URL.OFFICE_PROCEDURES,
    image: 'http://sfmi.in/images1/procedure.jpg',
    vietnamese: 'Thủ tục văn phòng',
  },
  {
    id: 9,
    topic: 'Electronics',
    phonetic: '/ɪˌlekˈtrɒnɪks/',
    classification: TOPIC_CLASSIFICATIONS.OFFICE_ISSUES.value,
    routerURL: ROUTER_URL.ELECTRONICS,
    image: 'https://keysight-h.assetsadobe.com/is/image/content/dam/keysight/en/img/other/home/industries_semiconductors-800x450.jpg',
    vietnamese: 'Thiết bị điện tử',
  },
  {
    id: 10,
    topic: 'Correspondence',
    phonetic: '/ˌkɒrəˈspɒndəns/',
    classification: TOPIC_CLASSIFICATIONS.OFFICE_ISSUES.value,
    routerURL: ROUTER_URL.CORRESPONDENCE,
    image: 'https://www.palaxo.com/wp-content/uploads/2014/01/eCorrespondence.jpg',
    vietnamese: 'Thư tín',
  },
  // personnel
  {
    id: 11,
    topic: 'Job Ads. and Recruiting',
    phonetic: '/dʒɒb/ /ˈædvətaɪzɪŋ/ /ənd/ /rɪˈkruːtɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.PERSONNEL.value,
    routerURL: ROUTER_URL.JOB_ADS_AND_RECRUITING,
    image: 'https://i0.wp.com/www.hiringpeople.co.uk/wp-content/uploads/2015/10/HIRING-PEOPLE-bg-mobile-Job-Board-01.jpg?fit=800%2C450&ssl=1',
    vietnamese: 'Quảng cáo việc làm và tuyển dụng',
  },
  {
    id: 12,
    topic: 'Applying and Interviewing',
    phonetic: '/əˈplaɪŋ/ /ənd/ /ˈɪntəvjuːɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.PERSONNEL.value,
    routerURL: ROUTER_URL.APPLYING_AND_INTERVIEWING,
    image: 'https://s18670.pcdn.co/wp-content/uploads/sites/2/2017/08/interview-tips-for-principals.png',
    vietnamese: 'Ứng tuyển và phỏng vấn',
  },
  {
    id: 13,
    topic: 'Hiring and Training',
    phonetic: '/ˈhaɪər/ /ənd/ /ˈtreɪnɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.PERSONNEL.value,
    routerURL: ROUTER_URL.HIRING_AND_TRAINING,
    image: 'http://nohaltd.com/wp-content/uploads/training.jpg',
    vietnamese: 'Tuyển dụng và đào tạo',
  },
  {
    id: 14,
    topic: 'Salaries and Benefits',
    phonetic: '/ˈsæləris/ /ənd/ /ˈbenɪfɪts/',
    classification: TOPIC_CLASSIFICATIONS.PERSONNEL.value,
    routerURL: ROUTER_URL.SALARIES_AND_BENEFITS,
    image: 'https://www.meritalkslg.com/wp-content/uploads/2016/08/pay-gap.jpg',
    vietnamese: 'Tiền lương và lợi ích',
  },
  {
    id: 15,
    topic: 'Promotions, Pensions and Awards',
    phonetic: '/prəˈməʊʃns/ /ˈpenʃns/ /ənd/ /əˈwɔːds/',
    classification: TOPIC_CLASSIFICATIONS.PERSONNEL.value,
    routerURL: ROUTER_URL.PROMOTIONS_PENSIONS_AND_AWARDS,
    image: 'https://www.theladders.com/wp-content/uploads/Equifax_Credit_Report-800x450.png',
    vietnamese: 'Khuyến mãi, lương hưu và giải thưởng',
  },
  // Purchasing
  {
    id: 16,
    topic: 'Shopping',
    phonetic: '/ˈʃɒpɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.PURCHASING.value,
    routerURL: ROUTER_URL.SHOPPING,
    image: 'http://www.freepressjournal.in/wp-content/uploads/2018/01/shopping.jpg',
    vietnamese: 'Mua sắm',
  },
  {
    id: 17,
    topic: 'Ordering Supplies',
    phonetic: '/ˈɔːdərɪŋ/ /səˈplaɪs/',
    classification: TOPIC_CLASSIFICATIONS.PURCHASING.value,
    routerURL: ROUTER_URL.ORDERING_SUPPLIES,
    image: 'https://mobilebytes.com/wp-content/uploads/2017/06/MobileBytes_OnlineOrdering_Blog_Sized.jpg',
    vietnamese: 'Đặt hàng nhà cung cấp',
  },
  {
    id: 18,
    topic: 'Shipping',
    phonetic: '/ˈʃɪpɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.PURCHASING.value,
    routerURL: ROUTER_URL.SHIPPING,
    image: 'https://media.licdn.com/media-proxy/ext?w=800&h=800&hash=y2Y8J306ZYEwaEXGCvJjQi3i1qI%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta5g-0R6nlh8Tw1It6a2FowGz60oISIfYC2G8G2f1spyfNT-tdoDScLShsgUbfSgBhlI_IfnwEXO5H_DVcfmqOJUAiMWmTuScXj9WLE4UtkZb-_YsCzsJ8MeCQ-TiYXMfl757bAmfEI3RY1kNBzUQ0b6FO7btD38h6BPebsDAL9hEC7AvoLMM01JNkfiVJs03nY5r7Xpu70TqrLbTB2wa2rf4JAKdP2IlGD3SCtFfif-93QGku0Xa13bjhae8VqKmGKMF0HOXxOzpfziMrlNY6U45zR81rPNgUHDNm9cmvUuKZuk_cjuSubD_blP40ZFK_j4x6NCD',
    vietnamese: 'Vận chuyển',
  },
  {
    id: 19,
    topic: 'Invoices',
    phonetic: '/ˈɪnvɔɪs/',
    classification: TOPIC_CLASSIFICATIONS.PURCHASING.value,
    routerURL: ROUTER_URL.INVOICES,
    image: 'http://onlinegstservices.com/Admin/Blog/Tax-Invoice-GST.jpg',
    vietnamese: 'Hóa đơn',
  },
  {
    id: 20,
    topic: 'Inventory',
    phonetic: '/ˈɪnvəntri/',
    classification: TOPIC_CLASSIFICATIONS.PURCHASING.value,
    routerURL: ROUTER_URL.INVENTORY,
    image: 'http://mediad.publicbroadcasting.net/p/wrkf/files/styles/medium/public/201701/inventory.jpg',
    vietnamese: 'Hàng tồn kho',
  },
  // Financing and budgeting
  {
    id: 21,
    topic: 'Banking',
    phonetic: '/ˈbæŋkɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.FINANCING_AND_BUDGETING.value,
    routerURL: ROUTER_URL.BANKING,
    image: 'https://www.ayninfotech.com/images/retail-banking/banking-2.jpg',
    vietnamese: 'Ngân hàng',
  },
  {
    id: 22,
    topic: 'Accounting',
    phonetic: '/əˈkaʊntɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.FINANCING_AND_BUDGETING.value,
    routerURL: ROUTER_URL.ACCOUNTING,
    image: 'https://www.academyoflearning.ab.ca/wp-content/uploads/2015/12/accounting-training-1-800x450.jpg',
    vietnamese: 'Kế toán',
  },
  {
    id: 23,
    topic: 'Investment',
    phonetic: '/ɪnˈvestmənt/',
    classification: TOPIC_CLASSIFICATIONS.FINANCING_AND_BUDGETING.value,
    routerURL: ROUTER_URL.INVESTMENTS,
    image: 'https://www.cpataxadvisorsllc.com/wp-content/uploads/sites/2558/2018/01/Investment.jpg',
    vietnamese: 'Đầu tư',
  },
  {
    id: 24,
    topic: 'Taxes',
    phonetic: '/tæks/',
    classification: TOPIC_CLASSIFICATIONS.FINANCING_AND_BUDGETING.value,
    routerURL: ROUTER_URL.TAXES,
    image: 'http://wpta.images.worldnow.com/images/15874569_G.jpg?auto=webp&disable=upscale&width=800&lastEditedDate=20180410103618',
    vietnamese: 'Thuế',
  },
  {
    id: 25,
    topic: 'Financial Statements',
    phonetic: '/faɪˈnænʃl/ /ˈsteɪtmənts/',
    classification: TOPIC_CLASSIFICATIONS.FINANCING_AND_BUDGETING.value,
    routerURL: ROUTER_URL.FINANCIAL_STATEMENTS,
    image: 'http://www.dailynews.lk/sites/default/files/news/2018/06/25/z_pv-Importance1.jpg',
    vietnamese: 'Báo cáo tài chính',
  },
  // Management issues
  {
    id: 26,
    topic: 'Property and Departments',
    phonetic: '/ˈprɒpəti/ /ənd/ /dɪˈpɑːtmənts/',
    classification: TOPIC_CLASSIFICATIONS.MANAGEMENT_ISSUES.value,
    routerURL: ROUTER_URL.PROPERTY_AND_DEPARTMENTS,
    image: 'https://systweak1.vo.llnwd.net/content/wp/systweakblogsnew/uploads/google-map.jpg',
    vietnamese: 'Tài sản và cơ sở',
  },
  {
    id: 27,
    topic: 'Board Meetings and Committees',
    phonetic: '/bɔːd/ /ˈmiːtɪŋs/ /ənd/ /kəˈmɪtiz/',
    classification: TOPIC_CLASSIFICATIONS.MANAGEMENT_ISSUES.value,
    routerURL: ROUTER_URL.BOARD_MEETINGS_AND_COMMITTEES,
    image: 'https://newgensoft.com/wp-content/uploads/2018/08/Changing-role-of-CIO.jpg',
    vietnamese: 'Các cuộc họp Hội đồng quản trị và các ủy ban',
  },
  {
    id: 28,
    topic: 'Quality Control',
    phonetic: '/ˈkwɒləti/ /kənˈtrəʊl/',
    classification: TOPIC_CLASSIFICATIONS.MANAGEMENT_ISSUES.value,
    routerURL: ROUTER_URL.QUALITY_CONTROL,
    image: 'http://acumenmd.com/wp-content/uploads/2016/02/quality-checkbox.jpg',
    vietnamese: 'Kiểm soát chất lượng',
  },
  {
    id: 29,
    topic: 'Product Development',
    phonetic: '/ˈprɒdʌkt/ /dɪˈveləpmənt/',
    classification: TOPIC_CLASSIFICATIONS.MANAGEMENT_ISSUES.value,
    routerURL: ROUTER_URL.PRODUCT_DEVELOPMENT,
    image: 'https://marketingland.com/wp-content/ml-loads/2015/05/team-meeting1-800x450.jpg',
    vietnamese: 'Phát triển sản phẩm',
  },
  {
    id: 30,
    topic: 'Renting and Leasing',
    phonetic: '/rentɪŋ/ /ənd/ /ˈliːsɪŋ/',
    classification: TOPIC_CLASSIFICATIONS.MANAGEMENT_ISSUES.value,
    routerURL: ROUTER_URL.RENTING_AND_LEASING,
    image: 'https://www.churchillsloan.co.uk/wp-content/uploads/News-Churchill-Sloan-CS-Buying-a-house-is-over-%C2%A32000-a-year-cheaper-than-renting-it-22-August-2018.png',
    vietnamese: 'Thuê và cho thuê',
  },
  // Restaurants and events
  {
    id: 31,
    topic: 'Selecting a Restaurant',
    phonetic: '/sɪˈlektɪŋ/ /ə/ /ˈrestrɒnt/',
    classification: TOPIC_CLASSIFICATIONS.RESTAURANTS_AND_EVENTS.value,
    routerURL: ROUTER_URL.SELECTING_A_RESTAURANT,
    image: 'https://miamicanpons.com/wp-content/uploads/2016/06/Restaurant_3.jpg',
    vietnamese: 'Lựa chọn một nhà hàng',
  },
  {
    id: 32,
    topic: 'Eating Out',
    phonetic: '/ˈiːtɪŋ/ /aʊt/',
    classification: TOPIC_CLASSIFICATIONS.RESTAURANTS_AND_EVENTS.value,
    routerURL: ROUTER_URL.EATING_OUT,
    image: 'https://i.dietdoctor.com/wp-content/uploads/2016/06/eating-out-horiz-1.jpg?auto=compress%2Cformat&w=800&h=450&fit=crop',
    vietnamese: 'Ăn uống',
  },
  {
    id: 33,
    topic: 'Ordering Lunch',
    phonetic: '/ˈɔːdərɪŋ/ /lʌntʃ/',
    classification: TOPIC_CLASSIFICATIONS.RESTAURANTS_AND_EVENTS.value,
    routerURL: ROUTER_URL.ORDERING_LUNCH,
    image: 'http://www.freepressjournal.in/wp-content/uploads/2017/06/pizza.jpg',
    vietnamese: 'Đặt hàng cho bữa trưa',
  },
  {
    id: 34,
    topic: 'Cooking as a Career',
    phonetic: '/ˈkʊkɪŋ/ /əz/ /ə/ /kəˈrɪə(r)/',
    classification: TOPIC_CLASSIFICATIONS.RESTAURANTS_AND_EVENTS.value,
    routerURL: ROUTER_URL.COOKING_AS_A_CAREER,
    image: 'https://i.kinja-img.com/gawker-media/image/upload/s--ZZNRWRxK--/c_scale,f_auto,fl_progressive,q_80,w_800/19cts4jh50kwdjpg.jpg',
    vietnamese: 'Nấu ăn như một nghề nghiệp',
  },
  {
    id: 35,
    topic: 'Events',
    phonetic: '/ɪˈvent/',
    classification: TOPIC_CLASSIFICATIONS.RESTAURANTS_AND_EVENTS.value,
    routerURL: ROUTER_URL.EVENTS,
    image: 'http://www.freepressjournal.in/wp-content/uploads/2016/11/Events.jpg',
    vietnamese: 'Sự kiện',
  },
  // Travel
  {
    id: 36,
    topic: 'General Travel',
    phonetic: '/ˈdʒenrəl/ /ˈtrævl/',
    classification: TOPIC_CLASSIFICATIONS.TRAVEL.value,
    routerURL: ROUTER_URL.GENERAL_TRAVEL,
    image: 'https://sanandres-colombia.com/wp-content/uploads/2016/06/travel-insurance.jpg',
    vietnamese: 'Tổng quát về du lịch',
  },
  {
    id: 37,
    topic: 'Airlines',
    phonetic: '/ˈeəlaɪns/',
    classification: TOPIC_CLASSIFICATIONS.TRAVEL.value,
    routerURL: ROUTER_URL.AIRLINES,
    image: 'https://marketingland.com/wp-content/ml-loads/2017/10/jet-airplane-takeoff-ss-1920-800x450.jpg',
    vietnamese: 'Hãng hàng không',
  },
  {
    id: 38,
    topic: 'Trains',
    phonetic: '/treɪns/',
    classification: TOPIC_CLASSIFICATIONS.TRAVEL.value,
    routerURL: ROUTER_URL.TRAINS,
    image: 'https://static.ffx.io/images/$width_800,$height_450/t_crop_auto/t_sharpen,q_auto,f_auto/23a55d63368e3adbb7de03a9e88d1729bf9177f8',
    vietnamese: 'Xe lửa',
  },
  {
    id: 39,
    topic: 'Hotels',
    phonetic: '/həʊˈtels/',
    classification: TOPIC_CLASSIFICATIONS.TRAVEL.value,
    routerURL: ROUTER_URL.HOTELS,
    image: 'http://static.asiawebdirect.com/m/bangkok/portals/bangkok-com/shared/teasersL/HOTELS/family-hotels/teaserMultiLarge/imageHilight/teaser.jpeg.jpg',
    vietnamese: 'Khách sạn',
  },
  {
    id: 40,
    topic: 'Car Rentals',
    phonetic: '/kɑː(r)/ /ˈrentls/',
    classification: TOPIC_CLASSIFICATIONS.TRAVEL.value,
    routerURL: ROUTER_URL.CAR_RENTALS,
    image: 'https://s.yimg.com/ny/api/res/1.2/tYj1sRDyzbNDIs85E9jaYw--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/http://media.zenfs.com/en-US/homerun/quartz.com/c9e2b842f400d4781d394abfda4c4a8d',
    vietnamese: 'Cho thuê xe',
  },
  // Entertainment
  {
    id: 41,
    topic: 'Movies',
    phonetic: '/ˈmuːvi/',
    classification: TOPIC_CLASSIFICATIONS.ENTERTAINMENT.value,
    routerURL: ROUTER_URL.MOVIES,
    image: 'http://www.asia96.com/wp-content/uploads/2017/04/Whats-On_Movies-Generic.jpg',
    vietnamese: 'Phim ảnh',
  },
  {
    id: 42,
    topic: 'Theater',
    phonetic: '/ˈθɪətə(r)/',
    classification: TOPIC_CLASSIFICATIONS.ENTERTAINMENT.value,
    routerURL: ROUTER_URL.THEATER,
    image: 'https://cdn.broadwaydirect.com/wp-content/uploads/2017/10/Haunted-Theater-800x450.jpg',
    vietnamese: 'Rạp hát',
  },
  {
    id: 43,
    topic: 'Music',
    phonetic: '/ˈmjuːzɪk/',
    classification: TOPIC_CLASSIFICATIONS.ENTERTAINMENT.value,
    routerURL: ROUTER_URL.MUSIC,
    image: 'https://bowtownmusic.com/wp/wp-content/uploads/2015/12/violin-and-music-book.jpg',
    vietnamese: 'Âm nhạc',
  },
  {
    id: 44,
    topic: 'Museums',
    phonetic: '/mjuːˈziːəms/',
    classification: TOPIC_CLASSIFICATIONS.ENTERTAINMENT.value,
    routerURL: ROUTER_URL.MUSEUMS,
    image: 'https://carnegiemnh.org/wp-content/uploads/2016/10/gift_store_visitors.png',
    vietnamese: 'Bảo tàng',
  },
  {
    id: 45,
    topic: 'Media',
    phonetic: '/ˈmiːdiə/',
    classification: TOPIC_CLASSIFICATIONS.ENTERTAINMENT.value,
    routerURL: ROUTER_URL.MEDIA,
    image: 'https://marketingland.com/wp-content/ml-loads/2017/10/social-media-1920-ss-800x450.jpg',
    vietnamese: 'Phương tiện truyền thông',
  },
  // Health
  {
    id: 46,
    topic: 'Doctor\'s Office',
    phonetic: '/ˈdɒktə(r)/ /s/ /ˈɒfɪs/',
    classification: TOPIC_CLASSIFICATIONS.HEALTH.value,
    routerURL: ROUTER_URL.DOCTOR_OFFICE,
    image: 'https://enticare.com/wp-content/uploads/2018/01/allergy-treatment-tests-enticare.jpg',
    vietnamese: 'Phòng khám',
  },
  {
    id: 47,
    topic: 'Dentist\'s Office',
    phonetic: '/ˈdentɪst/ /s/ /ˈɒfɪs/',
    classification: TOPIC_CLASSIFICATIONS.HEALTH.value,
    routerURL: ROUTER_URL.DENTIST_OFFICE,
    image: 'https://www.drjeffreystein.com/images/services/dental-exam.jpg',
    vietnamese: 'Phòng khám nha khoa',
  },
  {
    id: 48,
    topic: 'Health Insurance',
    phonetic: '/helθ/ /ɪnˈʃʊərəns/',
    classification: TOPIC_CLASSIFICATIONS.HEALTH.value,
    routerURL: ROUTER_URL.HEALTH_INSURANCE,
    image: 'http://www.expatmedia.net/wp-content/uploads/2016/05/healthinsurance.jpg',
    vietnamese: 'Bảo hiểm y tế',
  },
  {
    id: 49,
    topic: 'Hospitals',
    phonetic: '/ˈhɒspɪt(ə)ls/',
    classification: TOPIC_CLASSIFICATIONS.HEALTH.value,
    routerURL: ROUTER_URL.HOSPITALS,
    image: 'http://akincana.net/wp-content/uploads/2016/10/Hospitals.jpg',
    vietnamese: 'Bệnh viện',
  },
  {
    id: 50,
    topic: 'Pharmacy',
    phonetic: '/ˈfɑː(r)məsi/',
    classification: TOPIC_CLASSIFICATIONS.HEALTH.value,
    routerURL: ROUTER_URL.PHARMACY,
    image: 'http://www.dailynews.lk/sites/default/files/news/2016/10/24/z_p01-Pharmacy.jpg',
    vietnamese: 'Tiệm thuốc',
  },
];